lib-newlib: Update sigset_t structure to 1024 bits just as in musl
unikraft/lib-newlib pull request #15
Opened 2022-02-20 22:39 UTC by dragosargint

This PR changes the sigset_t structure from newlib to 1024 bits to solve conflicts that occur between musl and newlib when linked with uk_signal. Musl uses a 1024-bit mask, and newlib uses a 64-bit mask (i.e. an unsigned long).

2022-02-22 21:08 UTC, craciunoiuc requested changes
Hey @marcrittinghaus,

I tested the PR and it worked just fine with the others. Please also check it out

@dragosargint please reformat the commit message adding the required `selector` and some additional description

2022-02-22 21:39 UTC, dragosargint commented
Done!

2022-02-22 21:51 UTC, dragosargint commented
Done!

2022-02-23 08:53 UTC, craciunoiuc approved these changes
Hey @marcrittinghaus @dragosargint,

I think the PR looks good now. I hope I didn't miss anything.

At the time of this review, the CI/CD pipeline is blocked unfortunately. But everything should compile okay (cause it worked by hand).

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@gmail.com>

2022-03-24 08:48 UTC, marcrittinghaus commented
I don't get why a second definition of `__sigset_t` in `lib-newlib` has been introduced in the first place. But this is not your fault. Although, I think it would be better to clean up this mess, I will approve this change when all PRs in the series are ok.

2022-03-24 09:57 UTC, marcrittinghaus commented
So coming from the discussion in our community meeting, we should keep the definition in lib-newlib the same. Sorry for proposing the change in the first place but I only now get the whole picture with the other PRs referenced. 

However, we should still remove the duplicate definition of `is_sig_dfl` etc. when introducing it in `<uk/signal.h>` as suggested in https://github.com/unikraft/unikraft/pull/326. But let us have a discussion on the whole PR series first.

2022-05-26 08:39 UTC, razvand commented
This is superseded.

2022-05-26 08:39 UTC, closed without merging