/include: Fix macros in order to facilitate running apps on `AArch64`
unikraft/lib-newlib pull request #21
Opened 2022-08-03 16:05 UTC by mariasfiraiala

This PR fixes multiple issues regarding `newlib` support on `AArch64`.

2022-08-04 16:12 UTC, razvand requested changes
Hi, @mariasfiraiala , nice work figuring out the issues. See my comments.

2022-08-04 16:12 UTC, razvand commented on include/fcntl.h
> +#undef FNONBLOCK
This should actually happen for all architectures. [This commit](https://github.com/unikraft/lib-newlib/commit/58f9f3a3f7b5ca9c5f0c7c095e067abba29f5ed6) made the change for ARM, but it should happen for all architectures. `nolibc` defines the same value for both [x86_64](https://github.com/unikraft/unikraft/blob/staging/lib/nolibc/arch/x86_64/bits/fcntl.h) and for [ARM](https://github.com/unikraft/unikraft/blob/staging/lib/nolibc/arch/arm64/bits/fcntl.h). So, the two lines above should go both for x86_64 and for ARM. I think it's cleanest to duplicate them for each architectural `#ifdef`, connected to the other macros:

```
#undef FNONBLOCK
#undef O_NONBLOCK
#define FNONBLOCK 04000
#define O_NONBLOCK FNONBLOCK
```

I validated this working on my side.

2022-08-06 13:17 UTC, mogasergiu commented
Can confirm this fixes the issue for me as well.

2022-10-20 15:51 UTC, mogasergiu reviewed
Might be worth adding a Fixes tag here:
`Fixes: 58f9f3a3f7b5 ("include/fcntl.h: Replace O_NONBLOCK with new one on arm")`

2022-10-20 15:52 UTC, mariasfiraiala commented
> Might be worth adding a Fixes tag here: `Fixes: 58f9f3a3f7b5 ("include/fcntl.h: Replace O_NONBLOCK with new one on arm")`

Great suggestion, will do!

2022-10-20 16:06 UTC, mogasergiu approved these changes
Reviewed-by: Sergiu Moga <sergiu.moga@protonmail.com>

2022-10-21 09:59 UTC, skuenzer commented on include/fcntl.h
> -#define O_DIRECTORY  040000
Please note that `O_DIRECTORY` is a flag and should be only a single bit set. The value `0123456` is setting too many bits in its binary representation.

2022-10-22 07:12 UTC, mariasfiraiala commented
@skuenzer I've found a value for `O_DIRECTORY` that should fit our purpose: 0400000000 = 0x4000000. I've checked and has only one bit set, fits in `int` (used for the `open` function) and wasn't already used in [`_default_fcntl.h`](https://github.com/bminor/newlib/blob/master/newlib/libc/include/sys/_default_fcntl.h) or [`fcntl.h`](https://github.com/unikraft/lib-newlib/blob/staging/include/fcntl.h).

Hope you find it satisfactory as well.

2022-11-01 15:13 UTC, mogasergiu approved these changes
There don't seem to be any other conflicts, I did not pay that much attention last time - my apologies. I checked with some printf's inside `sys_open()`'s code and the flag seems to be correctly set and execution does land [where](https://github.com/unikraft/unikraft/blob/staging/lib/vfscore/syscalls.c#L179) I expected it to.

Reviewed-by: Sergiu Moga <sergiu.moga@protonmail.com>

2022-11-02 08:44 UTC, skuenzer approved these changes
Thanks a lot for your investigation. The changes look good!

Reviewed-by: Simon Kuenzer <simon@unikraft.io>

2022-11-04 13:13 UTC, razvand approved these changes
Thanks, @mariasfiraiala 

Reviewed-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>
Approved-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

2022-11-16 17:24 UTC, closed without merging